<template>
  <section class="h-screen w-screen fixed top-0">
    <div class="absolute z-20 w-full h-full">
      <div class="w-full h-full items-center justify-center flex">
        <div @click="close" class="absolute bg-gray-500 w-full h-full opacity-50"></div>
        <div class="bg-white p-2 rounded-md md:w-1/4 z-20">
          <span class="mb-4 text-lg font-bold uppercase flex w-full justify-center">Login</span>
          <section class="text-xs px-4 w-full">
            <button @click="loginWithGoogle" class="bg-red-500 p-2 w-full font-bold text-white">
              LOGIN WITH GOOGLE
            </button>
          </section>
          <form @submit.prevent="submit" class="w-full p-4 flex flex-col space-y-2">
            <span class="text-xs font-medium uppercase flex w-full justify-center">- OR -</span>
            <input ref="loginInput" v-model="form.email" placeholder="Email or Username" type="text"
              class="border w-full p-1 px-2" name="" id="" />
            <input v-model="form.password" placeholder="Password" type="password" class="border w-full p-1 px-2" name=""
              id="" />
            <button type="submit" class="
                p-1
                border
                bg-sky-500
                hover:bg-sky-600
                text-white
                w-1/3
                uppercase
                font-semibold
                rounded-full
                text-sm
                flex items-center justify-center
              ">
              <span v-if="!isLoading">
                Login
              </span>
              <svg v-else xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="200px"
                height="200px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid"
                class="h-4 w-4 animate-spin text-white">
                <circle cx="50" cy="50" fill="none" stroke="#ffffff" stroke-width="10" r="35"
                  stroke-dasharray="164.93361431346415 56.97787143782138" transform="matrix(1,0,0,1,0,0)"></circle>
                <!-- generated by https://loading.io/ -->
              </svg>
            </button>
          </form>
        </div>
      </div>
    </div>
  </section>
</template>

<script>
import { signInWithEmailAndPassword, GoogleAuthProvider, signInWithPopup } from "firebase/auth";
import auth from "../utilities/firebase";
import HomeVue from "../pages/Home.vue";

export default {
  mounted() {
    this.$refs.loginInput.focus();
  },
  data() {
    return {
      form: {
        email: "",
        password: "",
      },
      isLoading: false,
    };
  },
  methods: {
    submit() {
      this.isLoading = true
      signInWithEmailAndPassword(auth, this.form.email, this.form.password)
        .then((userCredential) => {
          const user = userCredential.user;
          console.log(user);
          this.form = {
            email: "",
            password: "",
          };
          this.$emit("close-login");
          this.isLoading = false;
        })
        .catch((error) => {
          const errorCode = error.code;
          const errorMessage = error.message;
          this.isLoading = false;
        });

    },
    close() {
      this.$emit("close-login");
    },
    async loginWithGoogle() {
      const provider = new GoogleAuthProvider();
      signInWithPopup(auth, provider)
        .then((result) => {
          // This gives you a Google Access Token. You can use it to access the Google API.
          const credential = GoogleAuthProvider.credentialFromResult(result);
          const token = credential.accessToken;
          // The signed-in user info.
          const user = result.user;
          console.log(result);
          // ...
        }).catch((error) => {
          // Handle Errors here.
          const errorCode = error.code;
          const errorMessage = error.message;
          // The email of the user's account used.
          const email = error.customData.email;
          // The AuthCredential type that was used.
          const credential = GoogleAuthProvider.credentialFromError(error);
          // ...
        });
    }
  },
};
</script>

<style>

</style>